services:
  - type: web
    name: screenshot-dashboard
    env: node
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm start
    nodeVersion: 20
    envVars:
      - key: NEXTAUTH_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false